import './globals.css'
import { Inter } from 'next/font/google'
import Topbar from '@/components/Navbars/Topbar'
import Leftbar from '@/components/Navbars/Leftbar'
import Buttombar from '@/components/Navbars/Buttombar'
import ReduxProvider from "@/components/ReduxProvider";
import ToastLayout from '@/components/ToastLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jobs Mela',
  description: 'Generated by JOY',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReduxProvider>
      <ToastLayout>
      <Topbar/>
      <main className='flex flex-row'>
      <Leftbar />
      <section className='main-container'>
        
      <div className='w-full max-w-4xl'>
        
        {children}
      
        </div>

      </section>
    </main>
    <Buttombar/>
    </ToastLayout>
    </ReduxProvider>
      </body>
    </html>
  )
}
